name: Main Build OpenWrt
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
        
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Installation depends
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y autoconf automake build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
        sudo -E apt-get -qq install -y asciidoc binutils gawk python3 subversion node-uglify-js p7zip-full libssl-dev texinfo upx libelf-dev device-tree-compiler 
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "America/Detroit"
    - name: Clone source code
      run: |
        git clone https://github.com/openwrt/openwrt
        cd openwrt
        wget -c https://github.com/gfunkmonk/openwrt/raw/main/diy-part1.sh
        wget -c https://github.com/gfunkmonk/openwrt/raw/main/diy-part2.sh
        chmod +x diy-part1.sh
        chmod +x diy-part2.sh        
        ./diy-part1.sh
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./diy-part2.sh
    - name: Generate config file
      run: |
        cd openwrt
        wget -c https://github.com/gfunkmonk/openwrt/raw/main/buildconfig
        cp buildconfig .config

- name: Start SSH via ngrok
  uses: P3TERX/ssh2actions@main
  with:
    mode: ngrok
   if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
  env:
    # After sign up on the https://ngrok.com
    # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
    NGROK_TOKEN: 2T0BRjf5DJEdY9TDECaGvWj7IYf_3p4CKAsYmDrauKhH9R4Jp
    
    # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
    # You can find this server region here: https://ngrok.com/docs#global-locations
    NGROK_REGION: us

    # This password you will use when authorizing via SSH
    SSH_PASSWORD: quondo
    # Send connection info to Telegram (optional)
    # You can find related documents here: https://core.telegram.org/bots
    # TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    # TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    
- name: Download package
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build
      run: |
        cd openwrt
        make -j$(nproc)
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin
        
